#!/bin/bash

#      _____       _       _ _   
#  ___|___ /      (_)_ __ (_) |_ 
# / __| |_ \ _____| | '_ \| | __|
# \__ \___) |_____| | | | | | |_ 
# |___/____/      |_|_| |_|_|\__|
# v0.1 - Andres Martinez
#
# Initialize an s3 bucket for local development quick an easy.
# Make sure to have awslocal installed, it is needed for the aliases to work.
#
# $ ./s3-init <bucker_name> <init_folder>
#

DIR="$(dirname "$(readlink -f "$0")")"
BUCKET_NAME="$1"
FILES_FOLDER="$2"

. "$DIR"/commons

[ -n "$BUCKET_NAME" ] && [ -n "$FILES_FOLDER" ] || log_throw 'Bucket name ($1) and files folder ($2) must be defiend'

log_bold "Initializing s3 for local development"
log_bold "-----------------------------------------------------"
"$DIR"/s3-create-bucket "$BUCKET_NAME" || exit 1
log ""
"$DIR"/s3-upload-file "$FILES_FOLDER" "$BUCKET_NAME" || exit 1
log ""
"$DIR"/s3-ls "$BUCKET_NAME" || exit 1
log_bold "-----------------------------------------------------"
log_bold "Successfully initialized s3 for local development"

exit 0
