#!/bin/bash

#      _____                                               _                _        _   
#  ___|___ /       _ __ ___ _ __ ___   _____   _____      | |__  _   _  ___| | _____| |_ 
# / __| |_ \ _____| '__/ _ \ '_ ` _ \ / _ \ \ / / _ \_____| '_ \| | | |/ __| |/ / _ \ __|
# \__ \___) |_____| | |  __/ | | | | | (_) \ V /  __/_____| |_) | |_| | (__|   <  __/ |_ 
# |___/____/      |_|  \___|_| |_| |_|\___/ \_/ \___|     |_.__/ \__,_|\___|_|\_\___|\__|
# v0.1 - Andres Martinez
#
# 
# Takes the container to the most recondite place of the filesystem, to the last folder and bursts it with bullets, the whole magazine, because otherwise he will eat a big flute garron.
# No seriously, it remove a given bucket from the running local-stack s3 instance with no previous confirmation, there is no going back.
# Make sure to have awslocal installed, it is needed for the aliases to work.
#
# $ ./s3-remove-bucket <bucket_name>
#

DIR="$(dirname "$(readlink -f "$0")")"
S3_BUCKET="$1"

. "$DIR"/commons

[ -n "$S3_BUCKET" ] || log_throw 'Bucket name ($1) must be defiend'

log_bold "Removing bucket $S3_BUCKET"
awslocal s3 rb s3://"$S3_BUCKET" --force || exit 1
log_bold "Successfully removed bucket $S3_BUCKET"

exit 0
